# Generated by Django 5.0.1 on 2024-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0007_alter_movies_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
