# Generated by Django 5.0.1 on 2024-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0008_alter_movies_actors_alter_movies_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(max_length=300),
        ),
    ]
