# Generated by Django 5.0.1 on 2024-03-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0010_moviereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
